# App service layered on top of the production internal services.
# Extends: compose.prod.yaml

services:
  inngest:
    command:
      - inngest
      - start
      - '--dir'
      - '/app'
      - '--sdk-url'
      - 'http://app:3000/api/inngest'
    extra_hosts: []
    networks:
      - durability

  migrate:
    pull_policy: build
    build:
      context: .
      target: migrate
    environment:
      POSTGRES_URL: postgresql://postgres:${POSTGRES_PASSWORD:?required}@postgres:5432/postgres
    volumes:
      - type: bind
        source: ./package.json
        target: /app/package.json
        read_only: true
      - type: bind
        source: ./drizzle.config.js
        target: /app/drizzle.config.js
        read_only: true
      - type: bind
        source: ./drizzle
        target: /app/drizzle
        read_only: true
      - type: bind
        source: ./src/lib/server/database/schema
        target: /app/src/lib/server/database/schema
        read_only: true
    networks:
      - database
    depends_on:
      # Wait for the app to start before running migrations. This ensures
      # the app is not broken before irreversibly applying migrations.
      app:
        condition: service_started
        required: true
      postgres:
        condition: service_healthy
        required: true
    restart: 'no'

  app:
    pull_policy: build
    build:
      context: .
      target: deploy
    ports:
      - 3000:3000
    environment:
      ORIGIN: ${ORIGIN:?required}
      PUBLIC_ORIGIN: ${ORIGIN:?required}
      POSTGRES_URL: postgresql://postgres:${POSTGRES_PASSWORD:?required}@postgres:5432/postgres
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID:?required}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET:?required}
      INNGEST_EVENT_KEY: ${INNGEST_EVENT_KEY:?required}
      INNGEST_SIGNING_KEY: ${INNGEST_SIGNING_KEY:?required}
      INNGEST_BASE_URL: http://inngest:8288
      OTEL_EXPORTER_OTLP_ENDPOINT: http://o2:5080/api/default
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:?required}
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    networks:
      - database
      - durability
      - telemetry
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      inngest:
        condition: service_healthy
        required: true
    restart: always

networks:
  durability:
