# Production overrides for observability and Drizzle services (o2, drizzle-gateway).
# docker compose --file compose.yaml --file compose.ci.yaml --file compose.prod.yaml up --detach --wait --build

services:
  o2:
    environment:
      ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL:?required}
      ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD:?required}

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:1.2.0
    ports:
      - 4983:4983
    environment:
      PORT: 4983
      STORE_PATH: /app
      MASTERPASS: ${DRIZZLE_MASTERPASS:?required}
    volumes:
      - drizzle-gateway:/app
    restart: always

volumes:
  drizzle-gateway:
