# Development overrides (`inngest` dev mode, `o2`, dev credentials).

services:
  postgres:
    environment:
      # Development-only credentials!
      POSTGRES_PASSWORD: password

  inngest:
    command:
      - inngest
      - dev
      - '--no-discovery'
      - '--sdk-url'
      - 'http://host.docker.internal:5173/api/inngest' # Vite

  o2:
    environment:
      # Development-only credentials!
      ZO_ROOT_USER_EMAIL: admin@example.com
      ZO_ROOT_USER_PASSWORD: password
