services:
  o2: !reset null
  inngest:
    command:
      - inngest
      - dev
      - '--no-discovery'
      - '--sdk-url'
      - 'http://host.docker.internal:4173/api/inngest'

volumes:
  open-observe: !reset null
