# Development overrides (`inngest` dev mode, `o2`, dev credentials).

services:
  postgres:
    environment:
      # Development-only credentials!
      POSTGRES_PASSWORD: password

  inngest:
    command:
      - inngest
      - dev
      - '--no-discovery'
      - '--sdk-url'
      - 'http://host.docker.internal:5173/api/inngest' # Vite

  o2:
    image: public.ecr.aws/zinclabs/openobserve:v0.50.3
    environment:
      ZO_DATA_DIR: /data
      # Development-only credentials!
      ZO_ROOT_USER_EMAIL: admin@example.com
      ZO_ROOT_USER_PASSWORD: password
    ports:
      - 5080:5080
    volumes:
      - open-observe:/data
    networks:
      - telemetry
    restart: always

volumes:
  open-observe:

networks:
  telemetry:
