# Production overrides (`inngest` prod mode, `redis`, observability, Drizzle).

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?required}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4.0
    command:
      - redis-server
      - '--appendonly'
      - 'yes'
    volumes:
      - redis:/data
    networks:
      - queue
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  inngest:
    command:
      - inngest
      - start
      - '--sqlite-dir'
      - '/app'
      - '--sdk-url'
      - 'http://host.docker.internal:4173/api/inngest'
    environment:
      INNGEST_EVENT_KEY: ${INNGEST_EVENT_KEY:?required}
      INNGEST_SIGNING_KEY: ${INNGEST_SIGNING_KEY:?required}
      INNGEST_REDIS_URI: redis://redis:6379
    volumes:
      - inngest:/app
    networks:
      - queue
    depends_on:
      redis:
        condition: service_healthy
        required: true
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:8288/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  o2:
    image: public.ecr.aws/zinclabs/openobserve:v0.50.3
    environment:
      ZO_DATA_DIR: /data
      ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL:?required}
      ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD:?required}
    ports:
      - 5080:5080
    volumes:
      - open-observe:/data
    networks:
      - telemetry
    restart: always

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:1.2.0
    ports:
      - 4983:4983
    environment:
      PORT: 4983
      STORE_PATH: /app
      MASTERPASS: ${DRIZZLE_MASTERPASS:?required}
    volumes:
      - drizzle-gateway:/app
    networks:
      - database
    restart: always

volumes:
  redis:
  inngest:
  open-observe:
  drizzle-gateway:

networks:
  queue:
  telemetry:
