# Base configuration with common fields (versions, ports, volumes).
name: drap

services:
  postgres:
    pull_policy: build
    build: ./docker/postgres
    ports:
      - host_ip: 127.0.0.1
        published: 5432
        target: 5432
        protocol: tcp
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - database
    restart: always
    healthcheck:
      test:
        - 'CMD'
        - 'pg_isready'
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 15s
      start_interval: 1s

  inngest:
    image: inngest/inngest:v1.23.0
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - queue
    ports:
      - host_ip: 127.0.0.1
        published: 8288
        target: 8288
        protocol: tcp
    restart: always
    healthcheck:
      test:
        - 'CMD'
        - 'inngest'
        - 'alpha'
        - 'doctor'
        - 'healthcheck'
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s
      start_interval: 1s

  otel-gui:
    image: ghcr.io/metafab/otel-gui:v1.3.0
    environment:
      HOST: 0.0.0.0
      PORT: 4318
      OTEL_GUI_MAX_TRACES: 10000
    ports:
      - host_ip: 127.0.0.1
        published: 4318
        target: 4318
        protocol: tcp
    networks:
      - telemetry
    restart: always

  rustfs:
    pull_policy: build
    build: ./docker/rustfs
    ports:
      - host_ip: 127.0.0.1
        published: 9000
        target: 9000
        protocol: tcp
      - host_ip: 127.0.0.1
        published: 9001
        target: 9001
        protocol: tcp
    volumes:
      - rustfs-data:/data
      - rustfs-logs:/logs
    networks:
      - storage
    restart: always
    healthcheck:
      test:
        - 'CMD'
        - '/health'
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s
      start_interval: 1s

  setup-bucket:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    profiles:
      - setup
    depends_on:
      rustfs:
        condition: service_healthy
        required: true
    command:
      - mb
      - --ignore-existing
      - drap/draft-student-avatar
    networks:
      - storage
    restart: 'no'

volumes:
  postgres:
  rustfs-data:
  rustfs-logs:

networks:
  database:
  queue:
  storage:
  telemetry:
