services:
  www:
    build: .
    profiles:
      - prod
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
  db:
    build: ./docker/postgres
    profiles:
      - dev
      - prod
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
volumes:
  postgres:
