services:
  www:
    build: .
    profiles:
      - prod
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'wget -q0- http://localhost:3000/']
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  db:
    build: ./docker/postgres
    profiles:
      - dev
      - prod
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
  redis:
    image: redis:8.0.3-alpine
    profiles:
      - dev
      - prod
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
volumes:
  postgres:
  redis:
