app = 'drap-app'
primary_region = 'sin'

[http_service]
processes = ['app']
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = 'shared-cpu-1x'
