app = 'drap-app'
primary_region = 'sin'

[processes]
app = '~/drap/app/build/index.js'
email = '--enable-source-maps ~/drap/email/dist/main.js'

[http_service]
processes = ['app']
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = 'shared-cpu-1x'
