allowBuilds:
  core-js-pure: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAgeStrict: true

minimumReleaseAgeExclude:
  - vite@8.1.4

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 525600 # 1 Year
