allowBuilds:
  core-js-pure: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAgeStrict: true

overrides:
  '@inngest/ai@0.1.7>@types/node': '-'
  '@inngest/ai@0.1.7>typescript': '-'
  'inngest@4.20.0>@opentelemetry/auto-instrumentations-node': '-'
  'inngest@4.20.0>@opentelemetry/context-async-hooks': '-'
  'inngest@4.20.0>@opentelemetry/instrumentation': '-'
  'inngest@4.20.0>@traceloop/instrumentation-anthropic': '-'

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 525600 # 1 Year
