allowBuilds:
  core-js-pure: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAgeExclude:
  - itertools@2.7.1
  - prettier-plugin-svelte@4.0.1

minimumReleaseAgeStrict: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 525600 # 1 Year
