allowBuilds:
  core-js-pure: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

blockExoticSubdeps: true

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 1440 # 1 day

minimumReleaseAgeExclude:
  - svelte@5.48.2

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - pino@9.14.0
  - ts-api-utils@2.3.0
  - undici-types@6.21.0
