allowBuilds:
  core-js-pure: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

blockExoticSubdeps: true

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 1440 # 1 day

minimumReleaseAgeExclude:
  - bits-ui@2.15.7
  - svelte-check@4.4.1

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 525600 # 1 year
