allowBuilds:
  core-js-pure: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

blockExoticSubdeps: true

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 1440 # 1 Day

minimumReleaseAgeExclude:
  - '@html-eslint/eslint-plugin@0.57.1'
  - '@html-eslint/parser@0.57.1'
  - '@sveltejs/kit@2.53.2'

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 525600 # 1 Year
