import assert from 'node:assert/strict';
import { env } from '$env/dynamic/private';

const { GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET, GOOGLE_OAUTH_REDIRECT_URI, GOOGLE_SERVICE_ISSUER, GOOGLE_SERVICE_SECRET, GOOGLE_SERVICE_SECRET_ID, GOOGLE_SERVICE_SCOPE } = env;
assert(typeof GOOGLE_OAUTH_CLIENT_ID !== 'undefined');
assert(typeof GOOGLE_OAUTH_CLIENT_SECRET !== 'undefined');
assert(typeof GOOGLE_OAUTH_REDIRECT_URI !== 'undefined');
assert(typeof GOOGLE_SERVICE_ISSUER !== 'undefined');
assert(typeof GOOGLE_SERVICE_SECRET !== 'undefined');
assert(typeof GOOGLE_SERVICE_SECRET_ID !== 'undefined');
assert(typeof GOOGLE_SERVICE_SCOPE !== 'undefined');

export default {
    OAUTH_CLIENT_ID: GOOGLE_OAUTH_CLIENT_ID,
    OAUTH_CLIENT_SECRET: GOOGLE_OAUTH_CLIENT_SECRET,
    OAUTH_REDIRECT_URI: GOOGLE_OAUTH_REDIRECT_URI,
    SERVICE_ISSUER: GOOGLE_SERVICE_ISSUER,
    SERVICE_SECRET: GOOGLE_SERVICE_SECRET,
    SERVICE_SECRET_ID: GOOGLE_SERVICE_SECRET_ID,
    SERVICE_SCOPE: GOOGLE_SERVICE_SCOPE,
};
